name: prune-env
dependencies:
  - python=3.8.0
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - pip
  - pip:
    - numpy==1.19.5
    - scipy==1.7.3
    - tensorflow-gpu==2.5.0
    - pandas==1.4.2
    - igraph==0.9.11
